controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

blog_list:
    path: /blog
    controller: App\Controller\BlogController::list